### PR TITLE
Import absolute_import everywhere

### PR DESCRIPTION
**Pull request by gdetrez**

### CODE REVIEW

**Comment by gdetrez** [comment]
Note: I'm planning to ignore everything stickler says in this PR :smiling_imp:

**Comment by gdetrez** [comment]
25tvcq

**Comment by local-minimum** [comment]
You have to resolve the conflicts, but otherwise I'm thinking that it should be OK. Have you tried starting SoM just to see that nothing obviously bad happens?

**Comment by gdetrez** [comment]
Conflicts fixed.
I'm not sure what "obviously bad" means... I checked that the system starts, and different pages are up but I haven't run more tests than that.

**Comment by local-minimum** [comment]
If you really wanna go the full stretch, check that an experiment runs from compilation to feature extraction

**Pull request merged**
